### ISSUE TITLE
AWS4 request signing not working to VinylDNS's liking

### ISSUE THREAD

**Issue by mdb** [vinyldns/vinyldns-js#5]
It appears `vinyldns-js` receives a 401 from the VinylDNS API due to a problem with the request signature. It's not clear whether the cause lives in `vinyldns-js`, `aws4` (the signing library used), or `vinyldns` itself.

```
> Error: 401: Authentication Failed: Request signature could not be validated
    at Request.request [as _callback] (/Users/mball0001/git/vinyldns-js/src/vinyldns.js:103:18)
    at Request.self.callback (/Users/mball0001/git/vinyldns-js/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/mball0001/git/vinyldns-js/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/mball0001/git/vinyldns-js/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

Steps to reproduce:

1. Start a VinylDNS at `localhost:9000` (This can be done by installing Docker, cloning [vinyldns](https://github.com/vinyldns/vinyldns), and running `bin/docker-up-vinyldns.sh --api-only --version 0.8.0` from within the `vinyldns` directory)
2. Create the following environment variables:
```
export VINYLDNS_API_SERVER=http://localhost:9000
export VINYLDNS_ACCESS_KEY_ID=okAccessKey
export VINYLDNS_SECRET_ACCESS_KEY=okSecretKey
```
3. Start the `vinyldns-js` REPL from within the `vinyldns-js` directory: `npm run repl`
4. Attempt to `getZones`: `vinyl.getZones().then(res => { console.log(res) }).catch(err => { console.log(err) })`

**Comment by mdb** [comment]
Fixed by PR #6
